export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_CURRENT_ADMIN = 'SET_CURRENT_ADMIN';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDE_BAR';
export const UPDATE_BANKS = 'UPDATE_BANKS';

export const CHANGE_NAV_BG = 'CHANGE_NAV_BG';
export const CHANGE_NAV_TXT = 'CHANGE_NAV_TXT';

export const UPDATE_ALERT = 'UPDATE_ALERT';
export const UPDATE_PRELOADER = 'UPDATE_PRELOADER';

export const UPDATE_LOAN = 'UPDATE_LOAN';
export const UPDATE_REQUEST_COMPLETE = 'UPDATE_REQUEST_COMPLETE';

